language: node_js

node_js:
  - 0.10
  - 0.11

before_script:
  - "npm install -g grunt-cli"
  - "npm install"

script:
  - "npm run build"
  - "npm test"

notifications:
  email:
    - ram@hiddentao.com
